version: "3"
services:
  cart_db:
    image: meroxbe/storage-service:shopapp
    ports:
      - 5001:5984
  cart_init_db:
    image: cart_init_db
    deploy:
      replicas: 1
      restart_policy:
        condition: none

