version: "3"
services:
  logs_db:
    image: meroxbe/storage-service:shopapp
    ports:
      - 7001:5984
  logging_init_db:
    image: logging_init_db
    deploy:
      replicas: 1
      restart_policy:
        condition: none

