version: "3"
services:
  ml_db:
    image: movielens_db
    ports:
      - 80:5984
  ml_init_db:
    image: movielens_init_db
    deploy:
      replicas: 1
      restart_policy:
        condition: none
